services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kntag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  anisette:
    image: dadoum/anisette-v3-server
    restart: always
    ports:
      - "6970:6969"

volumes:
  postgres_data:
